# fly.toml app configuration file generated for coolmate-mysql on 2024-05-27T12:08:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coolmate-mysql'
primary_region = 'hkg'

[build]
  image = 'mysql:8'

# [http_service]
#   internal_port = 3306
#   force_https = true
#   auto_stop_machines = true
#   auto_start_machines = true
#   min_machines_running = 0
#   processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'


[mounts]
  destination = "/data"
  source = "mysqldata"

[env]
  MYSQL_DATABASE = "coolmatedb"
  MYSQL_USER = "non_root_user"
